### ISSUE TITLE
Publish `0.2.1`

### ISSUE THREAD

**Issue by SNDST00M** [SNDST00M/material-dynmap#13]
## `0.2.1`

- [x] Cross-browser testing for `0.2.1` (Chrome, Edge, Safari, Firefox).
- [x] Update asset references.
- [ ] Create tag release for GitHub.
- [ ] Publish `0.2.1` to OpenUserJS.
- [ ] Publish `0.2.1` to NPM.

## Changelog

- Fix 3-up map type "layer" pane renderer.
- Adopt Minecraft color scheme.
- Fix for login style injection for sitewide script.
- Fix for compass contrast against dark areas.
- Copyedit bug report template.
