### ISSUE TITLE
Publish `0.2.2`

### ISSUE THREAD

**Issue by SNDST00M** [SNDST00M/material-dynmap#15]
## `0.2.2`

- [x] Cross-browser testing for `0.2.2` (Chrome, Edge, Safari, Firefox).
- [x] Update asset references.
- [x] Create tag release for GitHub.
- [x] Publish `0.2.2` to OpenUserJS.
- [x] Publish `0.2.2` to NPM.

## Changelog

- Fix for compass contrast against dark areas.
- Fix for sitewide script with login styles.
- Fix infinite recursion in Github Actions CI for Node 16.
- Fix package.json homepage and metadata.
