### ISSUE TITLE
Publish `0.3.0`

### ISSUE THREAD

**Issue by SNDST00M** [SNDST00M/material-dynmap#29]
## `0.3.0`

- [x] Cross-browser testing for `0.3.0` (Chrome, Edge, Safari, Firefox).
- [ ] Update asset references.
- [ ] Create tag release for GitHub.
- [ ] Publish `0.3.0` to OpenUserJS.
- [ ] Publish `0.3.0` to NPM.

## Changelog

- Add cross-platform installation guide.
- Add double run protection to entrypoints.
- Migrate from UNPKG to JSDelivr.
- Add `"material-dynmap.load"` event to `window` and `document`.
- Add Github and video hosts to userscript exclusion list.
- Add documentation for source code folder.
- Improve positioning and content of issue checklists.
