### ISSUE TITLE
Publish `0.8.1`

### ISSUE THREAD

**Issue by SNDST00M** [SNDST00M/material-dynmap#86]
## `0.8.1`

- [x] Cross-browser testing for `0.8.1` (Chrome, Edge, Safari, Firefox, Electron, Bukkit).
- [x] Update asset references.
- [x] Create tag release for GitHub.
- [ ] Publish `0.8.1` to OpenUserJS.
- [x] Publish `0.8.1` to NPM.

## Changelog

- Fix `java.lang.NoClassDefFoundError` plugin errors.
- Remove non-Minecraft plugin dependencies in JAR.
